### PR TITLE
Propagated changes across nginx adapter

### PR DESCRIPTION
**Pull request by b0id**
Signed-off-by: Colby Stoker <colby@iowolf.dev>

**Description** 

Following up "Externalizing the config #529" and externalizing to this (nginx) adapter.

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by b0id** [comment]
May need to rebase, I changed the sign-off email for the purposes of the PR, but it doesn't align with the email GitHub has assigned to keep emails private.  Let me know how to proceed.

**Comment by leecalcote** [comment]
Oh, that's interesting, @b0id. While we run into DCO challenges often, we don't come across this one much. No sweat here, though. Your commit sign off is valid. I'm manually overriding the DCO check now.

**Comment by b0id** [comment]
@leecalcote I will straighten it out before the next PR.

**Comment by b0id** [comment]
I just double checked this, looks like it is ok after today's conversation.

**Comment by leecalcote** [comment]
@jbyers19 fyi

**Comment by b0id** [comment]
Closing as this was addressed in another PR.

**Pull request closed without merging**
