### PR TITLE
Upgrade to Go 1.19

### PR DESCRIPTION
**Pull request by acald-creator**
Signed-off-by: Antonette Caldwell <pullmana8@gmail.com>

**Description**

This PR is related to https://github.com/meshery/meshery/issues/6220

**Notes for Reviewers**

- Update CI workflow
- Upgrade packages due to security concerns
- Removed mention of `meshes/proto`

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ x ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
```
Running [/home/runner/golangci-lint-1.49.0-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
[20](https://github.com/meshery/meshery-nginx-sm/actions/runs/3123592263/jobs/5066347800#step:3:22)
  level=error msg="Running error: context loading failed: failed to load packages: timed out to load packages: context deadline exceeded"
[21](https://github.com/meshery/meshery-nginx-sm/actions/runs/3123592263/jobs/5066347800#step:3:23)
  level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
```

**Comment by acald-creator** [comment]
Which I find that weird, because `golangci-lint` runs successfully locally. I will send up an  update in a moment.

**Comment by leecalcote** [comment]
> Which I find that weird, because `golangci-lint` runs successfully locally. I will send up an update in a moment.

I wonder if the version of golangci-lint is different between your local system and the workflow.

**Comment by acald-creator** [comment]
Possibly, I will change the version in the CI workflow.

**Comment by leecalcote** [comment]
@Revolyssup review

**Comment by Revolyssup** [comment]
@acald-creator Can you make sure the tests pass?

**Comment by acald-creator** [comment]
@Revolyssup sure I will work on it

**Comment by acald-creator** [comment]
Done

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
yay! :D

**Pull request merged**
