### PR TITLE
Fix logos

### PR DESCRIPTION
**Pull request by goldfishdolphin**
**Description**

This PR fixes #7491 in meshery [[Docs] Replace old Meshery logos](https://github.com/meshery/meshery/issues/7491)

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]
Looks great, @goldfishdolphin 👏

**Comment by vishalvivekm** [comment]
@goldfishdolphin would you mind sharing how the [Readme.md](https://github.com/meshery/meshery-nginx-sm#readme) looks like after your changes were merged
for me I see the logos to be broken:
Screenshot 2023-04-18 013823

**Comment by goldfishdolphin** [comment]
@vishalvivekm that is very strange as it is locally it is like this.
Screenshot 2023-04-18 at 11 08 47 am

Screenshot 2023-04-18 at 11 08 07 am

**Comment by vishalvivekm** [comment]
Hmm, @goldfishdolphin 
could you please once check https://github.com/meshery/meshery-nginx-sm#readme and confirm if you're too getting the same broken logos in readme as me ?

**Comment by vishalvivekm** [comment]
Sorry, due to some internet issues, the logos in the readme weren't being rendered, it's working well now, here's how it looks like after your changes
Screenshot from 2023-04-18 16-55-03


Here's some feedback : 
1. there's too much spacing between the first logo and the header "Meshery Adapter for NGINX Service Mesh"
2. the second meshery logo, the size is quite not what it should be: isn't it so small? @goldfishdolphin

**Comment by goldfishdolphin** [comment]
@vishalvivekm I agree with you. But it is still not appearing on browser as on vs code. Apparently img tag is not rendering dark/light  mode images that I replaced.

**Pull request merged**
